Corrections according to comments

diff --git a/examples/rank/integration-test-rank b/examples/rank/integration-test-rank
--- a/examples/rank/integration-test-rank
+++ b/examples/rank/integration-test-rank
@@ -12,6 +12,13 @@ LINE="=================================================================="
 # exit on any error
 #set -e
 
+check_file () {
+    if [ ! -f $1 ]; then
+        echo -e "${RED}File not found: $1${NC}"
+        exit 1
+    fi
+}
+
 echo -e "${GREEN}${LINE}"
 echo -e "Integration test [Rank] for The Universal Recommender."
 echo -e "If some step fails check that your engine.json file has been restored or look for it in 'user-engine.json'"
@@ -20,25 +27,15 @@ echo -e "${LINE}${NC}"
 echo -e "${GREEN}${LINE}"
 echo -e "Checking for needed files"
 echo -e "${LINE}${NC}"
-if [ ! -f examples/rank-engine.json ]; then
-    echo -e "${RED}File not found: examples/rank-engine.json${NC}"
-    exit 1
-fi
-
-if [ ! -f data/sample-rank-data.txt ]; then
-    echo -e "${RED}File not found: data/sample-rank-data.txt${NC}"
-    exit 1
-fi
 
 if [ -f user-engine.json ]; then
     echo -e "${RED}File user-engine.json found, this may be an error so we cannot replace engine.json${NC}"
     exit 1
 fi
 
-if [ ! -f data/rank-test-query-expected.txt ]; then
-    echo -e "${RED}File not found: data/rank-test-query-expected.txt${NC}"
-    exit 1
-fi
+check_file examples/rank/rank-engine.json
+check_file data/sample-rank-data.txt
+check_file data/rank-test-query-expected.txt
 
 echo -e "${GREEN}${LINE}"
 echo -e "Checking status, should exit if pio is not running."
@@ -57,9 +54,13 @@ echo -e "${LINE}${NC}"
 cp -n engine.json user-engine.json
 
 echo -e "${GREEN}${LINE}"
-echo -e "Moving examples/rank-engine.json to engine.json for integration test."
+echo -e "THE FIRST SERIAS OF TESTS"
 echo -e "${LINE}${NC}"
-cp examples/rank-engine.json engine.json
+
+echo -e "${GREEN}${LINE}"
+echo -e "Moving examples/rank/rank-engine.json to engine.json for integration test."
+echo -e "${LINE}${NC}"
+cp examples/rank/rank-engine.json engine.json
 
 echo -e "${GREEN}${LINE}"
 echo -e "Deleting ${APP_NAME} app data since the test is date dependent"
@@ -69,7 +70,7 @@ pio app data-delete ${APP_NAME} -f
 echo -e "${GREEN}${LINE}"
 echo -e "Importing data for integration test"
 echo -e "${LINE}${NC}"
-python examples/import_rank.py --access_key ${APP_ACCESS_KEY}
+python examples/rank/import_rank.py --access_key ${APP_ACCESS_KEY} --file './data/sample-rank-data.txt'
 
 echo -e "${GREEN}${LINE}"
 echo -e "Building and delpoying model"
@@ -79,7 +80,7 @@ pio train -- --executor-memory 1g --driver-memory 1g --master local
 
 echo -e "${GREEN}${LINE}"
 echo -e "Model will remain deployed after this test"
-nohup pio deploy > deploy.out &
+nohup pio deploy > deploy-rank.out &
 echo -e "Waiting 30 seconds for the server to start"
 echo -e "${LINE}${NC}"
 sleep 30
@@ -87,12 +88,7 @@ sleep 30
 echo -e "${GREEN}${LINE}"
 echo -e "Running test query."
 echo -e "${LINE}${NC}"
-./examples/multi-query-rank.sh > rank-query-test-result.out
-
-#this is due bug where first query had bad results
-#TODO: Investigate and squash
-
-#./examples/multi-query-handmade.sh > test.out
+./examples/rank/multi-query-rank.sh > rank-query-test-result.out
 
 echo -e "${GREEN}${LINE}"
 echo -e "Restoring engine.json"
@@ -110,6 +106,8 @@ DIFF_RESULT=`diff data/rank-test-query-expected.txt rank-query-test-result.out`
 if [[ -z "${DIFF_RESULT// }" ]]; then
     echo -e "${GREEN}${LINE}"
     echo -e "ALL TESTS PASS SUCCESS$"
+    rm rank-query-test-result.out
+    rm deploy-rank.out
 else
     echo -e "${RED}${LINE}"
     echo -e "ONE OR MORE TESTS FAILURE:"
